# Generated by Django 4.2.4 on 2023-08-26 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.ManyToManyField(to='store.item')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.profile')),
            ],
        ),
    ]
