# Generated by Django 4.2.4 on 2023-08-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_storeitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='items',
            field=models.ManyToManyField(to='store.item'),
        ),
        migrations.DeleteModel(
            name='StoreItem',
        ),
    ]
